### ISSUE TITLE
gulp4 support

### ISSUE THREAD

**Issue by sturichardson** [CodeineLabs/gulp-ngdocs-components#1]
I am attempting to use your package with gulp 4 however it appears as though gulp-ngdocs-components has some dependencies which need to be updated to a newer version to work with gulp 4.
Did you wish for me to create a pull request for this?

Cheers
Stu

**Comment by m-sanchez** [comment]
go for it, I did this library for an old project has been a while since I
don't update anything.

**Comment by paquettea** [comment]
I saw a merge on master occurring recently. I have an issue with gulp 4 and nodejs 12. I think the content of the merge you made on master would fix it for me. Can you please release the new version on NPM so that we can install it in a clean manner ?

Thanks

**Comment by m-sanchez** [comment]
Done
